# Change these first
owner: mifd670 # Your GitHub organization or username, where this repository lives
repo: rdpfisteruptime # The name of this repository

sites:
  - name: Georgetown Database
    url: https://database.playgeorge.town
    expectedStatusCodes:
      - 401
  - name: RDPFISTER Scaner
    url: https://feed.rdpfister.com
    assignees:
     - mifd670
  - name: Longwood Robotics Scouting
    url: http://frc-scouting.streamlit.app
    assignees:
     - mifd670
  - name: The Blue Alliance
    url: http://thebluealliance.com
    assignees:
     - mifd670

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rdpfister.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: RDPFISTER Uptime
  introTitle: "**RDPFISTER** status page for Ryan Pfister's assets.."
  introMessage: Welcome to my Status Page
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
i18n:
  footer: Ryan Pfister
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
